[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "COM", "N802", "T201", "ANN401"]

[tool.pyright]
reportAny = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportImportCycles = false
reportMissingModuleSource = false
reportPrivateUsage = false
reportUnusedCallResult = false
reportExplicitAny = false
